### ISSUE TITLE
Should print an error when metrics server is not installed

### ISSUE THREAD

**Issue by dbtek** [devopswe/ntop#8]
<img width="962" alt="image" src="https://github.com/devopswe/ntop/assets/310612/47ac15c4-7530-4f86-938a-b040901c28b5">

**Comment by devopswe** [comment]
Thanks I'll review that and add spesific logs in cases.

**Comment by devopswe** [comment]
Fixed. https://github.com/devopswe/ntop/commit/8355e7097a18b95c1cea26e47d5c5458579e4972
